/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: iLoveYourFace (https://sketchfab.com/iLoveYourFace)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/pastel-gaming-isometric-room-a1de2d38f5014f14835a1a193d12768c
Title: Pastel Gaming Isometric Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from 'gsap';
import { useGSAP } from '@gsap/react';

const Model = (props) => {
  const modelRef = useRef();

  useGSAP(() => {
    gsap.to(modelRef.current.rotation, {
      y: Math.PI * 2, 
      duration: 10,
      repeat: -1,     
      ease: 'none'    
    });
  }, []);

  const { nodes, materials } = useGLTF('/models/pastel_gaming_isometric_room.glb')
  return (
    <group {...props} dispose={null} ref={modelRef}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room_Material001_0.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room_Material002_0.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group position={[-40.229, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room001_Glass_0.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room001_Wall_0.geometry}
          material={materials.Wall}
        />
      </group>
      <group position={[0, -344.334, -380.667]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TvTable_Table_0.geometry}
          material={materials.Table}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Table_0.geometry}
          material={materials.Table}
          position={[0, 0.016, -1.107]}
        />
      </group>
      <group position={[0, -255.994, -381.177]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TV_tv_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TVScreen_tvScreen_0.geometry}
          material={materials.tvScreen}
          position={[0, -0.009, 0.138]}
        />
      </group>
      <group position={[-27.109, -427.055, -341.699]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Console_Material_0.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Console_tv_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Console_Poster_0.geometry}
          material={materials.Poster}
        />
      </group>
      <group position={[0, -367.329, 413.771]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Couch_Couch_0.geometry}
          material={materials.Couch}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_Couch_0.geometry}
          material={materials.Couch}
          position={[0, 3.019, 3.42]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_Couch_0.geometry}
          material={materials.Couch}
          position={[0.006, 1.056, -0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Couch_0.geometry}
          material={materials.Couch}
          position={[-1.363, 1.056, -0.25]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_Couch_0.geometry}
          material={materials.Couch}
          position={[1.377, 0.593, 0.474]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_Couch_0.geometry}
          material={materials.Couch}
          position={[0.006, 0.515, 0.497]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_Couch_0.geometry}
          material={materials.Couch}
          position={[-1.363, 0.514, 0.474]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_CoffeeTable_0.geometry}
          material={materials.CoffeeTable}
          position={[2.338, -0.071, -1.154]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_CoffeeTable_0.geometry}
          material={materials.CoffeeTable}
          position={[2.338, 1.501, -1.154]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_CoffeeTable_0.geometry}
          material={materials.CoffeeTable}
          position={[-2.368, 1.501, -1.154]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_CoffeeTable_0.geometry}
          material={materials.CoffeeTable}
          position={[-2.368, -0.071, -1.154]}
        />
      </group>
      <group position={[0, -413.108, -32.568]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table_CoffeeTable_0.geometry}
          material={materials.CoffeeTable}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[1.343, -0.574, -0.488]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[1.343, 0.525, -0.488]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[-1.311, -0.574, -0.488]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[-1.311, 0.525, -0.488]}
        />
      </group>
      <group position={[338.234, -498.27, 297.67]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_Sock1_0.geometry}
          material={materials.Sock1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_Sock2_0.geometry}
          material={materials.Sock2}
        />
      </group>
      <group position={[173.155, -495.382, 138.696]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_Sock1_0.geometry}
          material={materials.Sock1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_Sock2_0.geometry}
          material={materials.Sock2}
        />
      </group>
      <group position={[-54.93, -388.772, 12.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Cup_0.geometry}
          material={materials.material_21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Liquid_0.geometry}
          material={materials.Liquid}
        />
      </group>
      <group position={[75.68, -388.772, -21.799]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Cup_0.geometry}
          material={materials.material_21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Liquid_0.geometry}
          material={materials.Liquid}
        />
      </group>
      <group position={[37.159, -396.34, 25.805]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Cup_0.geometry}
          material={materials.material_21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Liquid_0.geometry}
          material={materials.Liquid}
        />
      </group>
      <group position={[62.923, -388.772, -1.11]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_Cup_0.geometry}
          material={materials.material_21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_Liquid_0.geometry}
          material={materials.Liquid}
        />
      </group>
      <group position={[70.013, -428.414, -332.651]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050_Material001_0.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050_PizzaBox_0.geometry}
          material={materials.PizzaBox}
        />
      </group>
      <group position={[386.122, -495.822, -344.099]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_Controller_0.geometry}
          material={materials.Controller}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
        />
      </group>
      <group position={[-432.541, -404.187, -11.581]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Drawers_CoffeeTable_0.geometry}
          material={materials.CoffeeTable}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube062_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[0.654, 1.437, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[0.405, 0.388, 0.513]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube072_Tissue_0.geometry}
          material={materials.Tissue}
          position={[0.577, 1.046, 0.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube073_Couch_0.geometry}
          material={materials.Couch}
          position={[0.669, 0.996, 0.735]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_Drawer2_0.geometry}
          material={materials.Drawer2}
          position={[0.042, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube064_Drawer2_0.geometry}
          material={materials.Drawer2}
          position={[0.454, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube065_Cup_0.geometry}
          material={materials.material_21}
          position={[0.678, -0.851, 0.618]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube066_1White_0.geometry}
          material={materials['1White']}
          position={[0.678, -0.851, 0.034]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_1White_0.geometry}
          material={materials['1White']}
          position={[0.678, -0.851, -0.604]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube068_1White_0.geometry}
          material={materials['1White']}
          position={[1.087, 0.874, 0.618]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube069_1White_0.geometry}
          material={materials['1White']}
          position={[0.678, 0.874, 0.034]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube070_1White_0.geometry}
          material={materials['1White']}
          position={[0.678, 0.874, -0.604]}
        />
      </group>
      <group position={[-366.409, -498.057, -367.027]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CatTree_Material001_0.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube074_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-0.453, 0.451, 1.216]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube075_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0.661, -0.606, 3.105]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[-0.452, 0.451, 0.307]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[0.661, -0.589, 1.279]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0.603, -0.31, 0.82]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[-0.452, 0.451, 2.061]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[0.434, 0.467, 1.114]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0.048, 0.259, 2.544]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube078_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-0.747, -0.284, 0.402]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube080_Material001_0.geometry}
          material={materials['Material.001']}
          position={[-0.166, -0.284, 0.402]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube081_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[-0.436, -0.445, 0.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[-0.436, -0.307, 0.397]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[-0.436, -0.169, 0.535]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube084_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
          position={[-0.436, -0.031, 0.673]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube085_Material001_0.geometry}
          material={materials['Material.001']}
          position={[0.272, -0.384, 1.805]}
        />
      </group>
      <group position={[-5.195, -399.924, -38.225]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Controller_Controller_0.geometry}
          material={materials.Controller}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube076__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.22, 0.016, 0.054]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube086__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.024, -0.021, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube087__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.028, 0.013, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube088__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.051, -0.008, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube089__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.001, -0.001, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube090__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.22, 0.016, 0.054]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube091__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.214, 0.082, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube092__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.214, 0.082, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube093__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.024, 0.054, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube094__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.024, 0.054, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube095__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.073, 0.008, 0.059]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube096__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.118, 0.014, 0.059]}
        />
      </group>
      <group position={[104.767, -399.924, 3.338]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Controller001_Controller_0.geometry}
          material={materials.Controller}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.16, -0.151, 0.054]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube097__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.032, 0.004, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube098__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.009, 0.03, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube099__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.04, 0.033, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube100__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.002, 0, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube101__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.16, -0.151, 0.054]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube102__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.205, -0.103, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube103__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.205, -0.103, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.024, 0.055, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.024, 0.055, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube106__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.055, -0.049, 0.059]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube107__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.09, -0.077, 0.059]}
        />
      </group>
      <group position={[97.766, -492.476, -200.26]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Controller002_Controller_0.geometry}
          material={materials.Controller}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.198, -0.097, 0.054]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube108__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.032, -0.006, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube109__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.018, 0.026, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube110__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.048, 0.019, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube111__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.002, -0.001, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube112__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.198, -0.097, 0.054]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube113__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.227, -0.037, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube114__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.227, -0.037, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube115__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.006, 0.059, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube116__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.006, 0.059, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube117__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.067, -0.03, 0.059]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube118__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.109, -0.047, 0.059]}
        />
      </group>
      <group position={[156.606, -324.281, -326.487]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Controller003_Controller_0.geometry}
          material={materials.Controller}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube119__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.218, -0.034, 0.054]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube120__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.029, -0.015, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube121__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.025, 0.019, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube122__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.052, 0.004, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube123__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.001, -0.001, 0.056]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube124__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.218, -0.034, 0.054]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube125__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.227, 0.032, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube126__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.227, 0.032, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube127__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.012, 0.058, -0.019]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube128__0.geometry}
          material={materials['Cube.076__0']}
          position={[0.012, 0.058, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube129__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.073, -0.009, 0.059]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube130__0.geometry}
          material={materials['Cube.076__0']}
          position={[-0.118, -0.013, 0.059]}
        />
      </group>
      <group position={[-469.864, -282.73, 100.174]} rotation={[-Math.PI / 2, 0, 0]} scale={23.735}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pot_CoffeeTableLegs_0.geometry}
          material={materials.CoffeeTableLegs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pot_PizzaBox_0.geometry}
          material={materials.PizzaBox}
        />
      </group>
      <group
        position={[-454.478, -304.753, -79.918]}
        rotation={[0.021, -0.75, 3.115]}
        scale={19.906}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PhotoFrame__0.geometry}
          material={materials['Cube.076__0']}
        />
        <group
          position={[-0.221, -1.572, -0.22]}
          rotation={[1.392, 0.344, -1.024]}
          scale={[1.536, 0.328, 1.536]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube134_CoffeeTableLegs_0.geometry}
            material={materials.CoffeeTableLegs}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube134_Poster1_0.geometry}
            material={materials.Poster1}
          />
        </group>
      </group>
      <group
        position={[-436.484, -304.716, -129.145]}
        rotation={[0.028, -0.527, 3.119]}
        scale={10.58}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PhotoFrame001__0.geometry}
          material={materials['Cube.076__0']}
        />
        <group
          position={[-0.221, -1.572, -0.22]}
          rotation={[1.392, 0.344, -1.024]}
          scale={[1.536, 0.328, 1.536]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube135_CoffeeTableLegs_0.geometry}
            material={materials.CoffeeTableLegs}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube135_Poster3_0.geometry}
            material={materials.Poster3}
          />
        </group>
      </group>
      <group position={[-435.893, -292.75, 130.998]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube136_Poster4_0.geometry}
          material={materials.Poster4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube136_Tissue_0.geometry}
          material={materials.Tissue}
        />
      </group>
      <group position={[-404.808, -457.829, 260.851]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_Table_0.geometry}
          material={materials.Table}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_Poster4_0.geometry}
          material={materials.Poster4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_Poster2_0.geometry}
          material={materials.Poster2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_Poster1_0.geometry}
          material={materials.Poster1}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Poster2_0.geometry}
        material={materials.Poster2}
        position={[335.465, -77.296, -495.936]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_Rug_0.geometry}
        material={materials.material_14}
        position={[0, -497.558, -28.119]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PizzaBox_PizzaBox_0.geometry}
        material={materials.PizzaBox}
        position={[-102.617, -391.054, -26.757]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019_PizzaBox_0.geometry}
        material={materials.PizzaBox}
        position={[-99.824, -400.698, -30.992]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021_Controller_0.geometry}
        material={materials.Controller}
        position={[-167.971, -421.311, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022_Table_0.geometry}
        material={materials.Table}
        position={[-162.375, -421.32, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-156.797, -421.311, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024_Table_0.geometry}
        material={materials.Table}
        position={[-151.182, -421.303, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-146.05, -421.313, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-140.682, -421.311, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027_Controller_0.geometry}
        material={materials.Controller}
        position={[-135.409, -421.311, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028_Table_0.geometry}
        material={materials.Table}
        position={[-129.791, -422.639, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-124.23, -420.671, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030_Table_0.geometry}
        material={materials.Table}
        position={[-118.611, -422.147, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031_Controller_0.geometry}
        material={materials.Controller}
        position={[-113.479, -422.136, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-108.119, -421.327, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033_1White_0.geometry}
        material={materials['1White']}
        position={[32.712, -437.981, -426.045]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-51.801, -410.851, -341.816]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[23.42, -403.02, -42.113]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036_Poster1_0.geometry}
        material={materials.Poster1}
        position={[23.42, -398.328, -42.113]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037_1White_0.geometry}
        material={materials['1White']}
        position={[-148.901, -327.358, -301.457]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004_Poster_0.geometry}
        material={materials.Poster}
        position={[-485.071, 159.594, 156.382]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005_Poster_0.geometry}
        material={materials.Poster}
        position={[-505.744, 156.672, -178.611]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006_Poster3_0.geometry}
        material={materials.Poster3}
        position={[62.746, 296.1, -495.936]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007_Poster4_0.geometry}
        material={materials.Poster4}
        position={[-292.262, 112.27, -495.936]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube051_Tissue_0.geometry}
        material={materials.Tissue}
        position={[-175.52, -344.829, 321.718]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube052_Tissue_0.geometry}
        material={materials.Tissue}
        position={[64.482, -340.355, 335.837]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube053_Tissue_0.geometry}
        material={materials.Tissue}
        position={[17.86, -488.559, 107.984]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Couch001_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[0, -367.329, 413.771]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube054_Tissue_0.geometry}
        material={materials.Tissue}
        position={[-494.042, 351.532, -17.63]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube055_1White_0.geometry}
        material={materials['1White']}
        position={[386.186, -143.961, -342.686]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038_Controller_0.geometry}
        material={materials.Controller}
        position={[108.726, -421.311, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039_Table_0.geometry}
        material={materials.Table}
        position={[114.323, -421.32, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[119.9, -421.311, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_Table_0.geometry}
        material={materials.Table}
        position={[125.515, -421.303, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[130.648, -421.313, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[136.016, -421.311, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube044_Controller_0.geometry}
        material={materials.Controller}
        position={[141.289, -421.311, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045_Table_0.geometry}
        material={materials.Table}
        position={[146.906, -422.639, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[152.468, -420.671, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047_Table_0.geometry}
        material={materials.Table}
        position={[158.087, -422.147, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048_Controller_0.geometry}
        material={materials.Controller}
        position={[163.219, -422.136, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[168.579, -421.327, -314.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-103.109, -421.311, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057_Table_0.geometry}
        material={materials.Table}
        position={[-97.494, -421.303, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube058_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-92.362, -421.313, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059_Table_0.geometry}
        material={materials.Table}
        position={[-86.826, -422.147, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube060_Controller_0.geometry}
        material={materials.Controller}
        position={[-81.695, -422.136, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061_CoffeeTableLegs_0.geometry}
        material={materials.CoffeeTableLegs}
        position={[-73.216, -421.327, -313.298]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011_Poster1_0.geometry}
        material={materials.Poster1}
        position={[21.526, 5.538, -495.936]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LampCable_1White_0.geometry}
        material={materials['1White']}
        position={[-77.502, -490.742, 29.823]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PowerPlug_1White_0.geometry}
        material={materials['1White']}
        position={[110.892, -323.846, -395.873]}
        rotation={[-Math.PI / 2, -1.348, 0]}
        scale={6.465}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ControllerCable_1White_0.geometry}
        material={materials['1White']}
        position={[-77.502, -490.742, 29.823]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Tissue_0.geometry}
        material={materials.Tissue}
        position={[-498.952, -478.448, -22.752]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018_Tissue_0.geometry}
        material={materials.Tissue}
        position={[-498.952, 477.264, -22.752]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube131_Tissue_0.geometry}
        material={materials.Tissue}
        position={[-22.687, -478.448, -500.832]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube132_Tissue_0.geometry}
        material={materials.Tissue}
        position={[-22.687, 477.264, -500.832]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube133_Cactus_0.geometry}
        material={materials.Cactus}
        position={[-470.673, -252.044, 100.3]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009_PizzaBox_0.geometry}
        material={materials.PizzaBox}
        position={[-412.873, -294.199, 142.348]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012_PizzaBox_0.geometry}
        material={materials.PizzaBox}
        position={[-420.105, -451.43, 244.429]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013_PizzaBox_0.geometry}
        material={materials.PizzaBox}
        position={[-415.244, -445.483, 259.372]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert001_1White_0.geometry}
        material={materials['1White']}
        position={[94.886, -400.589, 9.498]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert002_1White_0.geometry}
        material={materials['1White']}
        position={[88.808, -491.069, -196.263]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert005_1White_0.geometry}
        material={materials['1White']}
        position={[146.121, -321.052, -326.345]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube137_1White_0.geometry}
        material={materials['1White']}
        position={[-80.375, -435.94, -433.213]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube138_1White_0.geometry}
        material={materials['1White']}
        position={[-109.933, -427.739, -419.496]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube139_1White_0.geometry}
        material={materials['1White']}
        position={[-97.304, -427.739, -425.356]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube140_1White_0.geometry}
        material={materials['1White']}
        position={[-84.345, -427.739, -431.37]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube141_1White_0.geometry}
        material={materials['1White']}
        position={[-69.573, -427.739, -438.226]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/models/pastel_gaming_isometric_room.glb');

export default Model;
